#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "arn_messager"
name = "ARN-Messager"
description.en = "Bot which enables multiple Matrix users to use a single IM account over Mautrix bridges."
description.fr = "Robot qui permet à plusieurs comptes Matrix de mutualiser un unique compte de messagerie instantanée tierce via les bridges Mautrix."

version = "1.2~ynh1"

maintainers = ["Gredin67","zamentur","Thatoo"]

[upstream]
license = "AGPL-3.0-or-later"
admindoc = "https://code.ffdn.org/arn/arn-messager#configuration-file"
userdoc = "https://arn-fai.net/fr/blog/arn-messager-contact-whatsapp-sans-donner-facebook#mise-en-pratique-de-darn-messager"
code = "https://code.ffdn.org/arn/arn-messager"
fund = "https://don.arn-fai.net/"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr_FR", "en_US"]
    default = "en_US"

    [install.homeserver]
    ask.en = "Choose the local Matrix Home Server instance to communicate with ARN-Messager"
    ask.fr = "Choisissez l'instance locale de Home Server Matrix qui doit communiquer avec ARN-Messager"
    help.en = "Only synapse supported. If you installed synapse only once, then leave default value synapse."
    help.fr = "Seul Synapse est supporté. Si vous n'avez installé qu'une fois synapse, gardez la valeur par défaut synapse."
    type = "string"
    example = "synapse__2"
    default = "synapse"

    [install.botname]
    ask.en = "Choose a name for the ARN-Messager Bot"
    ask.fr = "Choisissez un nom pour le Robot ARN-Messager"
    type = "string"
    example = "ARN-Messager"
    default = "ARN-Messager"

    [install.botaccount]
    ask.en = "Give the local synapse user name for the ARN-Messager bot"
    ask.fr = "Donnez le nom d'utilisateur synapse local pour le robot ARN-Messager"
    help.en = "You should create a user before install. Invite @arnmessager:localsynapse.servername from an authorized Matrix account to start bridging. Give the matrix server_name, not the full domain/url."
    help.fr = "Vous devez créer un utilisateur avant l'installation. Inviter @arnmessager:localsynapse.servername depuis un compte Matrix autorisé pour démarrer une passerelle. Donner le nom du serveur matrix, pas le domaine/url complet."
    type = "string"
    example = "arnmessager"
    default = "arnmessager"

    [install.botpassword]
    ask.en = "Give the password for the ARN-Messager bot"
    ask.fr = "Donnez le mot-de-passe pour le robot ARN-Messager"
    help.en = "You should create a user before install."
    help.fr = "Vous devez créer un utilisateur avant l'installation."
    type = "string"

    [install.botnumber]
    ask.en = "Phone number of the Signal/Whatsapp relay account. Use +33612345678 formatting"
    ask.fr = "Numéro de téléphone du compte Signal/Whatsapp relai. Au format +33612345678"
    help.en = "You will have to scan the QR code sent by the bridge with the Signal/Whatsapp App linked to this number."
    help.fr = "Il faudra scanner le QR code envoyé par le bridge avec l'appli Signal/Whatsapp liée à ce numéro."
    type = "string"
    example = "+33612345678"
    default = "+33612345678"

    [install.botusers]
    ask.en = "Choose Matrix instances authorized to invite the ARN-Messager bot"
    ask.fr = "Choisissez les instances Matrix autorisées à inviter le robot ARN-Messager"
    help.en = "Usually local server. Give the Matrix server_name, not the full domain/URL."
    help.fr = "Typiquement le serveur local. Donner le server_name du serveur Matrix, pas le domaine/URL complet."
    type = "string"
    example = "synapse.servername"
    default = "domain.tld"

    [install.admins]
    ask.en = "Choose Matrix users or instances authorized to send control commands to the bridges over ARN-Messager"
    ask.fr = "Choisissez les comptes ou instances Matrix autorisés à contrôler les passerelles à travers ARN-Messager"
    help.en = "Usually local synapse server admin. Give the full Matrix address (MXID)."
    help.fr = "Typiquement les admins du serveur synapse local. Donner l'identifiant Matrix complet (MXID)."
    type = "string"
    example = "@admin:synapse_server.name"
    default = "@admin:domain.tld"

    [install.bridge]
    ask.en = "Relay bridge instance to be managed via its bot"
    ask.fr = "Instance de passerelle relai à gérer via son robot"
    help.en = "List of instant messaging (social) network that you want to relay."
    help.fr = "Liste des réseaux (sociaux) de messagerie instantanée que vous voulez relayer."
    type = "string"
    example = "mautrix_whatsapp"
    default = "mautrix_signal"

    [install.encryption]
    ask.en = "Allow end-to-bridge encryption?"
    ask.fr = "Permettre le chiffrement entre Synapse et le bridge ?"
    type = "boolean"
    help.en = "Must be activated if one Relay bridge instance is using E2B."
    help.fr = "A activer si une des passerelles relai utilise E2B."
    default = false

[resources]

    [resources.sources]

    [resources.sources.main]
    # This will pre-fetch the asset which can then be deployed during the install/upgrade scripts with :
    #    ynh_setup_source --dest_dir="$install_dir"
    # You can also define other assets than "main" and add --source_id="foobar" in the previous command
    #in_subdir = false
    #extract = false
    #rename = "mautrix-whatsapp"
    url = "https://code.ffdn.org/arn/arn-messager/-/archive/testing/arn-messager-testing.tar.gz"
    sha256 = "7604fb105f3c3983c5d53db46f9e753022837360d81ee1de0db533ee56204a14"
    autoupdate.strategy = "latest_gitlab_release"

    [resources.system_user]

    [resources.install_dir]
    